language: java
jdk:
  - oraclejdk8
services:
  - redis
  - postgresql
  - mongodb

before_script:
  - psql -c 'create database odm;' -U postgres
  - psql -c 'create table if not exists psqlusers (id serial primary key, name varchar(255), age int);' -d odm -U postgres

install: true